server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/front-end-developer/microservice-spring-cloud-server-config-via-git
          search-paths:
            - station*
